### ISSUE TITLE
这里有一个类似的刷新

### ISSUE THREAD

**Issue by ckrgithub** [xmuSistone/AlipayPullRefresh#1]
https://github.com/ckrgithub/CollapsingRefresh，估计改造一下可以触摸顶部，也可以下拉刷新

**Comment by xmuSistone** [comment]
@ckrgithub 我下载你的Apk体验了下，其实还是有些不一样的，改造起来要费很大的力气。我在Readme里面也提及官方控件存在各种水土不服。如果从一开始就使用CoordinatorLayout，可能会是无休止地拆东墙补西墙，泥足深陷。反倒是，从一开始就破釜沉舟，开天辟地似的改造，更容易解脱束缚，迎来新生。
